### ISSUE TITLE
キャラクターページの作成

### ISSUE THREAD

**Issue by opionoid** [RinUeyama/peregre#7]
## TODO

- [x] メイキング→シートへのルーティング
- [x] 「保存」「読み込み」ボタンを用意してデータを読み書き
- [x] シート情報の暗号化（一般的なユーザーがURLパスから容易に任意のキャラを作成できない程度まで。コード見て復元できる人はこのリポジトリクローンしてカスタマイズできるだろうから複雑なことはしない）
- [x] 戦闘モード: スキル使用前、性能をボタン下部に出す
- [x] 戦闘モード: スキル使用時、コピペまたは／かつディスコードに書き出す設定
- [x] 編集モード: 武器やアビリティ設定（横カルーセルよりメイン武器／サブ武器で切り替えられる一覧画面にしたい。モーダルは他のスキルが見づらくなるから不採用。武器はUltと通常で分離して最大9個表示にする）

### キャラクターシートはリスト化すべきか

 一度に何枚も使うなら必要。つまり参加者は不要で進行役は必要。進行役が用いるNPCの情報はシナリオページ上に簡易版シートとして存在させるためここでは扱わない。

### NPCシートと共通化すべきか

構造が似ているようで制約が大きく異なるのでキャラクターページとはデータのみならずコンポーネントも独立させる。（ディスコードのWebhook のみ共通化しておいてもいいが、これはいずれにせよ utils に入る）

**Comment by opionoid** [comment]
url に保存するよりは json形式で保存して（難読化は別にかませる）Recoil を通してやりとりするほうがはるかに見通しがいい & URL が綺麗

**Comment by opionoid** [comment]
仕様更新

### 削除
- シート情報をURLに保存（シード値、名前、武器とアビリティの構成）
-  シート情報が含まれたURLではメイキングではなくシートを直接表示

### 新規
- 「保存」「読み込み」ボタンを用意してデータを読み書き
